// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dufqdszjnorgjixelynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZnFkc3pqbm9yZ2ppeGVseW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwMzM5MzIsImV4cCI6MjA4MjYwOTkzMn0.JutQTi-cFetWl4Frcpz5klTbHw3tg9Z01W6ats4yC7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});